/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.3/samples
 * This project uses @Incubating APIs which are subject to change.
 */

 plug-ins {
  id( "org.sonarqube" ) versão "4.3.1.3277"
}

sonar {
  propriedades {
    propriedade( "sonar.projectKey" , "1743575-5_hello-world" )
    propriedade( "sonar.organização" , "1743575-5" )
    propriedade( "sonar.host.url" , "https://sonarcloud.io" )
  }
}
